[package]
name = "ritardatreno"
version = "0.1.0"
authors = ["Enrico204 <enrico204@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
structopt = "0.3.21"
trenitalia = "0.3.4"
colored = "1.9.3"
chrono = "0.4.19"